server:
    port: 8084

spring:
    application:
        name: coffee
    datasource:
        url: jdbc:postgresql://localhost:5432/coffee
        username: postgres
        password: 1
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        generate-ddl: true
        show-sql: true
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB
    mvc:
        hiddenmethod:
            filter:
                enabled: true
